### ISSUE TITLE
Update requirements.txt file

### ISSUE THREAD

**Issue by joaoamcarvalho** [deepmind/mc_gradients#3]
Hi,
I am unable to run the experiments by following the instructions in the README.

Here's what I get when I run `python -m monte_carlo_gradients.gradients_estimators_test`

```
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.1; Detected an installation of version 1.15.0-rc2. Please upgrade TensorFlow to proceed
```

However, if I update to TF >= 2.1 some other parts of the code break with this version.

Could you update the requirements.txt file with dependencies that should work?

More info: Ubuntu 18.04, Python 3.7.6, no GPU

**Comment by mihaelacr** [comment]
I just pushed a change which fixed it for me. Can you confirm this works for you now?

Thanks!

**Comment by joaoamcarvalho** [comment]
`python -m monte_carlo_gradients.gradient_estimators_test` still gives me an error.
```
AttributeError: module 'tensorflow_probability.python.distributions' has no attribute 'DoublesidedMaxwell'
```

But the main works, `python -m monte_carlo_gradients.main`.

Thanks!

**Comment by mihaelacr** [comment]
Yes, unfortunately the DoubleMaxwell Distribution is not present in the older versions of TFP, which are compatible with TF1. 

Will close this for now, but proper fix will be more involved.

**Comment by mihaelacr** [comment]
@jacarvalho FYI I now fixed the tests too. This entails you can use the measure valued gradient estimation too, and thus everything should be available.

**Comment by joaoamcarvalho** [comment]
Great! thanks!
